---

stages:
  - test
  - build

include:
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


.python-base:
  stage: test
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
  image: python:3.12-alpine
  before_script:
    - mkdir --parents "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install -e .[dev,rest,mongo,redis,event-bus,taskiq]
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


Ruff:
  extends: .python-base
  script:
    ruff check saltbox_sdk


Mypy:
  extends: .python-base
  script:
    mypy saltbox_sdk
