name: Sync PR to GitLab


on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


jobs:
  get-pr-number:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: pr-number
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: pr
        run: echo "number=$(cat pr_number.txt)" >> "$GITHUB_OUTPUT"
    outputs:
      pr_number: ${{ steps.pr.outputs.number }}


  sync:
    needs: get-pr-number
    uses: saltbox-pro/.github/.github/workflows/sync-pr-to-gitlab.yml@main
    with:
      pr_number: ${{ needs.get-pr-number.outputs.pr_number }}
    secrets:
      GITLAB_PR_SYNC_TOKEN: ${{ secrets.GITLAB_PR_SYNC_TOKEN }}

